env:
  # Telegram
  TG_CHAT: ENCRYPTED[!d1a2e49aa9263890015770d199fc1daf88fa007a0838c6b28df0f041eaae7c7d06bd9e631f1a3127b8eb90c49ab0edcc!]
  TG_TOKEN: ENCRYPTED[!1f897f49e592e3efce91c812dd254351be0b48e843dfbb80bb15d63cbf519a004b015d2c0919c0b507e890aae16b1687!]

task:
  name: "KERNEL BUILD CI by RullV2"
  skip: $CIRRUS_BRANCH == 'master'

  timeout_in: 120m
  container:
      image: ubuntu
      privileged: true
      cpu: 8
      memory: 10G
      
  setup_script:
      - apt update
      - apt upgrade -y
      - apt install wget git -y
      - wget https://raw.githubusercontent.com/TheUnknownName/toolFW/main/setup.sh
      - bash setup.sh

  build_script:
      - wget https://raw.githubusercontent.com/Ismasrull/Kernel-Builder-CI/master/build.sh
      - chmod +x build.sh
      - ./build.sh ${CIRRUS_WORKING_DIR}/name-kernel.txt
